name: PR Checks

on:
  pull_request:

jobs:
  pr-checks:
    name: PR Checks (clippy, fmt, test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: Check formatting
        run: |
          rustup component add rustfmt
          cargo fmt -- --check 